# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/peko/prj/aitarget/uap-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/peko/prj/aitarget/uap-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peko/prj/aitarget/uap-cpp/CMakeFiles /home/peko/prj/aitarget/uap-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peko/prj/aitarget/uap-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named objlib

# Build rule for target.
objlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 objlib
.PHONY : objlib

# fast build rule for target.
objlib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/build
.PHONY : objlib/fast

#=============================================================================
# Target rules for targets named uap-cpp-static

# Build rule for target.
uap-cpp-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uap-cpp-static
.PHONY : uap-cpp-static

# fast build rule for target.
uap-cpp-static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uap-cpp-static.dir/build.make CMakeFiles/uap-cpp-static.dir/build
.PHONY : uap-cpp-static/fast

#=============================================================================
# Target rules for targets named uap-cpp-shared

# Build rule for target.
uap-cpp-shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uap-cpp-shared
.PHONY : uap-cpp-shared

# fast build rule for target.
uap-cpp-shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uap-cpp-shared.dir/build.make CMakeFiles/uap-cpp-shared.dir/build
.PHONY : uap-cpp-shared/fast

#=============================================================================
# Target rules for targets named bench

# Build rule for target.
bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench
.PHONY : bench

# fast build rule for target.
bench/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/build
.PHONY : bench/fast

#=============================================================================
# Target rules for targets named parse

# Build rule for target.
parse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse
.PHONY : parse

# fast build rule for target.
parse/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/build
.PHONY : parse/fast

#=============================================================================
# Target rules for targets named parse_memcached

# Build rule for target.
parse_memcached: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse_memcached
.PHONY : parse_memcached

# fast build rule for target.
parse_memcached/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse_memcached.dir/build.make CMakeFiles/parse_memcached.dir/build
.PHONY : parse_memcached/fast

#=============================================================================
# Target rules for targets named generate_buckets

# Build rule for target.
generate_buckets: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_buckets
.PHONY : generate_buckets

# fast build rule for target.
generate_buckets/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_buckets.dir/build.make CMakeFiles/generate_buckets.dir/build
.PHONY : generate_buckets/fast

#=============================================================================
# Target rules for targets named parse-dur

# Build rule for target.
parse-dur: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parse-dur
.PHONY : parse-dur

# fast build rule for target.
parse-dur/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse-dur.dir/build.make CMakeFiles/parse-dur.dir/build
.PHONY : parse-dur/fast

MurmurHash2.o: MurmurHash2.cpp.o
.PHONY : MurmurHash2.o

# target to build an object file
MurmurHash2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/MurmurHash2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse_memcached.dir/build.make CMakeFiles/parse_memcached.dir/MurmurHash2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_buckets.dir/build.make CMakeFiles/generate_buckets.dir/MurmurHash2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse-dur.dir/build.make CMakeFiles/parse-dur.dir/MurmurHash2.cpp.o
.PHONY : MurmurHash2.cpp.o

MurmurHash2.i: MurmurHash2.cpp.i
.PHONY : MurmurHash2.i

# target to preprocess a source file
MurmurHash2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/MurmurHash2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse_memcached.dir/build.make CMakeFiles/parse_memcached.dir/MurmurHash2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_buckets.dir/build.make CMakeFiles/generate_buckets.dir/MurmurHash2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse-dur.dir/build.make CMakeFiles/parse-dur.dir/MurmurHash2.cpp.i
.PHONY : MurmurHash2.cpp.i

MurmurHash2.s: MurmurHash2.cpp.s
.PHONY : MurmurHash2.s

# target to generate assembly for a file
MurmurHash2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/MurmurHash2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse_memcached.dir/build.make CMakeFiles/parse_memcached.dir/MurmurHash2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_buckets.dir/build.make CMakeFiles/generate_buckets.dir/MurmurHash2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse-dur.dir/build.make CMakeFiles/parse-dur.dir/MurmurHash2.cpp.s
.PHONY : MurmurHash2.cpp.s

UaParser.o: UaParser.cpp.o
.PHONY : UaParser.o

# target to build an object file
UaParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/UaParser.cpp.o
.PHONY : UaParser.cpp.o

UaParser.i: UaParser.cpp.i
.PHONY : UaParser.i

# target to preprocess a source file
UaParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/UaParser.cpp.i
.PHONY : UaParser.cpp.i

UaParser.s: UaParser.cpp.s
.PHONY : UaParser.s

# target to generate assembly for a file
UaParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/UaParser.cpp.s
.PHONY : UaParser.cpp.s

base64.o: base64.cpp.o
.PHONY : base64.o

# target to build an object file
base64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/base64.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse_memcached.dir/build.make CMakeFiles/parse_memcached.dir/base64.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_buckets.dir/build.make CMakeFiles/generate_buckets.dir/base64.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse-dur.dir/build.make CMakeFiles/parse-dur.dir/base64.cpp.o
.PHONY : base64.cpp.o

base64.i: base64.cpp.i
.PHONY : base64.i

# target to preprocess a source file
base64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/base64.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse_memcached.dir/build.make CMakeFiles/parse_memcached.dir/base64.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_buckets.dir/build.make CMakeFiles/generate_buckets.dir/base64.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse-dur.dir/build.make CMakeFiles/parse-dur.dir/base64.cpp.i
.PHONY : base64.cpp.i

base64.s: base64.cpp.s
.PHONY : base64.s

# target to generate assembly for a file
base64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/base64.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse_memcached.dir/build.make CMakeFiles/parse_memcached.dir/base64.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_buckets.dir/build.make CMakeFiles/generate_buckets.dir/base64.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse-dur.dir/build.make CMakeFiles/parse-dur.dir/base64.cpp.s
.PHONY : base64.cpp.s

benchmarks/UaParserBench.o: benchmarks/UaParserBench.cpp.o
.PHONY : benchmarks/UaParserBench.o

# target to build an object file
benchmarks/UaParserBench.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/benchmarks/UaParserBench.cpp.o
.PHONY : benchmarks/UaParserBench.cpp.o

benchmarks/UaParserBench.i: benchmarks/UaParserBench.cpp.i
.PHONY : benchmarks/UaParserBench.i

# target to preprocess a source file
benchmarks/UaParserBench.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/benchmarks/UaParserBench.cpp.i
.PHONY : benchmarks/UaParserBench.cpp.i

benchmarks/UaParserBench.s: benchmarks/UaParserBench.cpp.s
.PHONY : benchmarks/UaParserBench.s

# target to generate assembly for a file
benchmarks/UaParserBench.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/benchmarks/UaParserBench.cpp.s
.PHONY : benchmarks/UaParserBench.cpp.s

generate_buckets.o: generate_buckets.cpp.o
.PHONY : generate_buckets.o

# target to build an object file
generate_buckets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_buckets.dir/build.make CMakeFiles/generate_buckets.dir/generate_buckets.cpp.o
.PHONY : generate_buckets.cpp.o

generate_buckets.i: generate_buckets.cpp.i
.PHONY : generate_buckets.i

# target to preprocess a source file
generate_buckets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_buckets.dir/build.make CMakeFiles/generate_buckets.dir/generate_buckets.cpp.i
.PHONY : generate_buckets.cpp.i

generate_buckets.s: generate_buckets.cpp.s
.PHONY : generate_buckets.s

# target to generate assembly for a file
generate_buckets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_buckets.dir/build.make CMakeFiles/generate_buckets.dir/generate_buckets.cpp.s
.PHONY : generate_buckets.cpp.s

internal/AlternativeExpander.o: internal/AlternativeExpander.cpp.o
.PHONY : internal/AlternativeExpander.o

# target to build an object file
internal/AlternativeExpander.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/internal/AlternativeExpander.cpp.o
.PHONY : internal/AlternativeExpander.cpp.o

internal/AlternativeExpander.i: internal/AlternativeExpander.cpp.i
.PHONY : internal/AlternativeExpander.i

# target to preprocess a source file
internal/AlternativeExpander.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/internal/AlternativeExpander.cpp.i
.PHONY : internal/AlternativeExpander.cpp.i

internal/AlternativeExpander.s: internal/AlternativeExpander.cpp.s
.PHONY : internal/AlternativeExpander.s

# target to generate assembly for a file
internal/AlternativeExpander.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/internal/AlternativeExpander.cpp.s
.PHONY : internal/AlternativeExpander.cpp.s

internal/Pattern.o: internal/Pattern.cpp.o
.PHONY : internal/Pattern.o

# target to build an object file
internal/Pattern.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/internal/Pattern.cpp.o
.PHONY : internal/Pattern.cpp.o

internal/Pattern.i: internal/Pattern.cpp.i
.PHONY : internal/Pattern.i

# target to preprocess a source file
internal/Pattern.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/internal/Pattern.cpp.i
.PHONY : internal/Pattern.cpp.i

internal/Pattern.s: internal/Pattern.cpp.s
.PHONY : internal/Pattern.s

# target to generate assembly for a file
internal/Pattern.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/internal/Pattern.cpp.s
.PHONY : internal/Pattern.cpp.s

internal/ReplaceTemplate.o: internal/ReplaceTemplate.cpp.o
.PHONY : internal/ReplaceTemplate.o

# target to build an object file
internal/ReplaceTemplate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/internal/ReplaceTemplate.cpp.o
.PHONY : internal/ReplaceTemplate.cpp.o

internal/ReplaceTemplate.i: internal/ReplaceTemplate.cpp.i
.PHONY : internal/ReplaceTemplate.i

# target to preprocess a source file
internal/ReplaceTemplate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/internal/ReplaceTemplate.cpp.i
.PHONY : internal/ReplaceTemplate.cpp.i

internal/ReplaceTemplate.s: internal/ReplaceTemplate.cpp.s
.PHONY : internal/ReplaceTemplate.s

# target to generate assembly for a file
internal/ReplaceTemplate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/internal/ReplaceTemplate.cpp.s
.PHONY : internal/ReplaceTemplate.cpp.s

internal/SnippetIndex.o: internal/SnippetIndex.cpp.o
.PHONY : internal/SnippetIndex.o

# target to build an object file
internal/SnippetIndex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/internal/SnippetIndex.cpp.o
.PHONY : internal/SnippetIndex.cpp.o

internal/SnippetIndex.i: internal/SnippetIndex.cpp.i
.PHONY : internal/SnippetIndex.i

# target to preprocess a source file
internal/SnippetIndex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/internal/SnippetIndex.cpp.i
.PHONY : internal/SnippetIndex.cpp.i

internal/SnippetIndex.s: internal/SnippetIndex.cpp.s
.PHONY : internal/SnippetIndex.s

# target to generate assembly for a file
internal/SnippetIndex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/objlib.dir/build.make CMakeFiles/objlib.dir/internal/SnippetIndex.cpp.s
.PHONY : internal/SnippetIndex.cpp.s

parse-dur.o: parse-dur.cpp.o
.PHONY : parse-dur.o

# target to build an object file
parse-dur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse-dur.dir/build.make CMakeFiles/parse-dur.dir/parse-dur.cpp.o
.PHONY : parse-dur.cpp.o

parse-dur.i: parse-dur.cpp.i
.PHONY : parse-dur.i

# target to preprocess a source file
parse-dur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse-dur.dir/build.make CMakeFiles/parse-dur.dir/parse-dur.cpp.i
.PHONY : parse-dur.cpp.i

parse-dur.s: parse-dur.cpp.s
.PHONY : parse-dur.s

# target to generate assembly for a file
parse-dur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse-dur.dir/build.make CMakeFiles/parse-dur.dir/parse-dur.cpp.s
.PHONY : parse-dur.cpp.s

parse.o: parse.cpp.o
.PHONY : parse.o

# target to build an object file
parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/parse.cpp.o
.PHONY : parse.cpp.o

parse.i: parse.cpp.i
.PHONY : parse.i

# target to preprocess a source file
parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/parse.cpp.i
.PHONY : parse.cpp.i

parse.s: parse.cpp.s
.PHONY : parse.s

# target to generate assembly for a file
parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse.dir/build.make CMakeFiles/parse.dir/parse.cpp.s
.PHONY : parse.cpp.s

parse_memcached.o: parse_memcached.cpp.o
.PHONY : parse_memcached.o

# target to build an object file
parse_memcached.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse_memcached.dir/build.make CMakeFiles/parse_memcached.dir/parse_memcached.cpp.o
.PHONY : parse_memcached.cpp.o

parse_memcached.i: parse_memcached.cpp.i
.PHONY : parse_memcached.i

# target to preprocess a source file
parse_memcached.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse_memcached.dir/build.make CMakeFiles/parse_memcached.dir/parse_memcached.cpp.i
.PHONY : parse_memcached.cpp.i

parse_memcached.s: parse_memcached.cpp.s
.PHONY : parse_memcached.s

# target to generate assembly for a file
parse_memcached.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parse_memcached.dir/build.make CMakeFiles/parse_memcached.dir/parse_memcached.cpp.s
.PHONY : parse_memcached.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bench"
	@echo "... generate_buckets"
	@echo "... objlib"
	@echo "... parse"
	@echo "... parse-dur"
	@echo "... parse_memcached"
	@echo "... uap-cpp-shared"
	@echo "... uap-cpp-static"
	@echo "... MurmurHash2.o"
	@echo "... MurmurHash2.i"
	@echo "... MurmurHash2.s"
	@echo "... UaParser.o"
	@echo "... UaParser.i"
	@echo "... UaParser.s"
	@echo "... base64.o"
	@echo "... base64.i"
	@echo "... base64.s"
	@echo "... benchmarks/UaParserBench.o"
	@echo "... benchmarks/UaParserBench.i"
	@echo "... benchmarks/UaParserBench.s"
	@echo "... generate_buckets.o"
	@echo "... generate_buckets.i"
	@echo "... generate_buckets.s"
	@echo "... internal/AlternativeExpander.o"
	@echo "... internal/AlternativeExpander.i"
	@echo "... internal/AlternativeExpander.s"
	@echo "... internal/Pattern.o"
	@echo "... internal/Pattern.i"
	@echo "... internal/Pattern.s"
	@echo "... internal/ReplaceTemplate.o"
	@echo "... internal/ReplaceTemplate.i"
	@echo "... internal/ReplaceTemplate.s"
	@echo "... internal/SnippetIndex.o"
	@echo "... internal/SnippetIndex.i"
	@echo "... internal/SnippetIndex.s"
	@echo "... parse-dur.o"
	@echo "... parse-dur.i"
	@echo "... parse-dur.s"
	@echo "... parse.o"
	@echo "... parse.i"
	@echo "... parse.s"
	@echo "... parse_memcached.o"
	@echo "... parse_memcached.i"
	@echo "... parse_memcached.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

